# Run linting.
name: Verify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16', '17']
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache
      - name: Linting
        run: |
          yarn lint
