# Run linting.
name: Verify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16', '18']
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Check commit message
        if: ${{ github.event_name == 'pull_request' }}
        run: yarn commitlint ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}

      - name: Linting
        run: yarn lint
