# Run linting.
name: Verify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16', '18']
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Check commit message
        if: ${{ github.event_name == 'pull_request' }}
        run: yarn commitlint ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}

      - name: Linting
        run: yarn lint
